#!/bin/bash

# This script adds execute permission to all subdirectories of the current directory for the owner, group owner, and all other users.

# Use find command to search for all subdirectories in the current directory
# Add execute permission to owner, group owner, and all other users using chmod command
# Ignore regular files

find . -type d -exec chmod a+x {} + 
